// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// Support both VITE_SUPABASE_ANON_KEY (standard) and VITE_SUPABASE_PUBLISHABLE_KEY (legacy)
const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// ── Startup validation ──────────────────────────────────────────────────────
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error(
    "[Supabase] MISSING ENV VARS",
    { url: SUPABASE_URL, keySet: Boolean(SUPABASE_ANON_KEY) }
  );
} else {
  const keyType = SUPABASE_ANON_KEY.startsWith("eyJ") ? "jwt/anon ✅" : "publishable key ⚠️ (may not work for RPC)";
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Bypass navigator.locks to prevent infinite hanging when a tab crashes and holds the lock
    lock: async (name: string, acquireTimeout: number, fn: () => Promise<any>) => {
      return await fn();
    },
  }
});